spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://150.158.115.139:3306/miaosha?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000 #当资源池连接用尽后，调用者的最大等待时间(单位为毫秒) -1
    minIdle: 500  #资源池确保最少空闲的连接数；默认值：0；
    timeBetweenEvictionRunsMillis: 60000 #空闲资源的检测周期(单位为毫秒)；默认值：-1：不检测；使用建议：建议设置，周期自行选择，也可以默认也可以使用下面JedisPoolConfig中的配置
    minEvictableIdleTimeMillis: 300000 #资源池中资源最小空闲时间(单位为毫秒)，达到此值后空闲资源将被移除；默认值：1000 60 30 = 30分钟；
    validationQuery: select 'x'
    testWhileIdle: true #是否开启空闲资源监测；默认值：false；使用建议：true
    testOnBorrow: false #向资源池借用连接时是否做连接有效性检测(ping)，无效连接会被移除；使用建议：业务量很大时候建议设置为false(多一次ping的开销)。
    testOnReturn: false #向资源池归还连接时是否做连接有效性检测(ping)，无效连接会被移除；默认值：false；使用建议：业务量很大时候建议设置为false(多一次ping的开销)。
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  rabbitmq:
    host: 150.158.115.139
    port: 5672
    username: test
    password: test
    virtual-host: /
    #消费者数量
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        #消费者每次从队列获取的消息数量
        prefetch: 1
        #消费者自动启动
        auto-startup: true
        #消费失败，自动重新入队
        default-requeue-rejected: true
    #启动发送重试
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

#redis150.158.115.139
redis:
  host: 150.158.115.139
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 3

#mybatis
mybatis:
  type-aliases-package: com.pomo.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/pomo/miaosha/dao/*.xml







